import { make_keyword } from "./helpers.js";

// ─── Architecture note ────────────────────────────────────────────────────────
// ALL keywords — including dialect-specific ones — MUST be defined here in the
// base grammar.  Tree-sitter's keyword extraction (`ts_lex_keywords`) only runs
// on the root grammar file; a keyword defined solely in a dialect grammar is
// added to the symbol table but bypasses `ts_lex_keywords`, so the lexer treats
// it as a plain identifier in ambiguous positions and parse trees break.
//
// Dialect grammars re-declare the keywords they use with
//   `token(prec(1, make_keyword("...")))``
// This gives their lexer states the right preference without needing to move
// the definition out of the base.  The dialect-specific comment sections below
// (Delta, Unity Catalog, Snowflake, Hive, BigQuery, PostgreSQL types, …) exist
// for exactly this reason: the keywords live here because tree-sitter requires
// it, not because they are ANSI SQL.
// ─────────────────────────────────────────────────────────────────────────────

export default {

  keyword_select: _ => make_keyword("select"),
  keyword_delete: _ => make_keyword("delete"),
  keyword_insert: _ => make_keyword("insert"),
  keyword_replace: _ => make_keyword("replace"),
  keyword_update: _ => make_keyword("update"),
  keyword_truncate: _ => make_keyword("truncate"),
  keyword_merge: _ => make_keyword("merge"),
  keyword_show: _ => make_keyword("show"),
  keyword_unload: _ => make_keyword("unload"),
  keyword_into: _ => make_keyword("into"),
  keyword_overwrite: _ => make_keyword("overwrite"),
  keyword_values: _ => make_keyword("values"),
  keyword_value: _ => make_keyword("value"),
  keyword_matched: _ => make_keyword("matched"),
  keyword_set: _ => make_keyword("set"),
  keyword_from: _ => make_keyword("from"),
  keyword_left: _ => make_keyword("left"),
  keyword_right: _ => make_keyword("right"),
  keyword_inner: _ => make_keyword("inner"),
  keyword_full: _ => make_keyword("full"),
  keyword_outer: _ => make_keyword("outer"),
  keyword_cross: _ => make_keyword("cross"),
  keyword_join: _ => make_keyword("join"),
  keyword_lateral: _ => make_keyword("lateral"),
  keyword_natural: _ => make_keyword("natural"),
  keyword_on: _ => make_keyword("on"),
  keyword_off: _ => make_keyword("off"),
  keyword_where: _ => make_keyword("where"),
  keyword_order: _ => make_keyword("order"),
  keyword_group: _ => make_keyword("group"),
  keyword_partition: _ => make_keyword("partition"),
  keyword_by: _ => make_keyword("by"),
  keyword_having: _ => make_keyword("having"),
  keyword_desc: _ => make_keyword("desc"),
  keyword_asc: _ => make_keyword("asc"),
  keyword_limit: _ => make_keyword("limit"),
  keyword_offset: _ => make_keyword("offset"),
  keyword_primary: _ => make_keyword("primary"),
  keyword_create: _ => make_keyword("create"),
  keyword_alter: _ => make_keyword("alter"),
  keyword_change: _ => make_keyword("change"),
  keyword_analyze: _ => make_keyword("analyze"),
  keyword_explain: _ => make_keyword("explain"),
  keyword_verbose: _ => make_keyword("verbose"),
  keyword_modify: _ => make_keyword("modify"),
  keyword_drop: _ => make_keyword("drop"),
  keyword_add: _ => make_keyword("add"),
  keyword_table: _ => make_keyword("table"),
  keyword_tables: _ => make_keyword("tables"),
  keyword_view: _ => make_keyword("view"),
  keyword_policy: _ => make_keyword("policy"),
  keyword_column: _ => make_keyword("column"),
  keyword_columns: _ => make_keyword("columns"),
  keyword_materialized: _ => make_keyword("materialized"),
  keyword_tablespace: _ => make_keyword("tablespace"),
  keyword_split: _ => make_keyword("split"),
  keyword_tablets: _ => make_keyword("tablets"),
  keyword_sequence: _ => make_keyword("sequence"),
  keyword_increment: _ => make_keyword("increment"),
  keyword_minvalue: _ => make_keyword("minvalue"),
  keyword_maxvalue: _ => make_keyword("maxvalue"),
  keyword_none: _ => make_keyword("none"),
  keyword_owned: _ => make_keyword("owned"),
  keyword_start: _ => make_keyword("start"),
  keyword_restart: _ => make_keyword("restart"),
  keyword_reverse: _ => make_keyword("reverse"),
  keyword_usage: _ => make_keyword("usage"),
  keyword_rollup: _ => make_keyword("rollup"),
  keyword_cube: _ => make_keyword("cube"),
  keyword_grouping: _ => make_keyword("grouping"),
  keyword_sets: _ => make_keyword("sets"),
  keyword_key: _ => make_keyword("key"),
  keyword_keys: _ => make_keyword("keys"),
  keyword_flow: _ => make_keyword("flow"),
  keyword_upsert: _ => make_keyword("upsert"),
  keyword_duplicate: _ => make_keyword("duplicate"),
  keyword_as: _ => make_keyword("as"),
  keyword_distinct: _ => make_keyword("distinct"),
  keyword_constraint: _ => make_keyword("constraint"),
  keyword_filter: _ => make_keyword("filter"),
  keyword_cast: _ => make_keyword("cast"),
  keyword_separator: _ => make_keyword("separator"),
  keyword_case: _ => make_keyword("case"),
  keyword_when: _ => make_keyword("when"),
  keyword_then: _ => make_keyword("then"),
  keyword_else: _ => make_keyword("else"),
  keyword_end: _ => make_keyword("end"),
  keyword_in: _ => make_keyword("in"),
  keyword_and: _ => make_keyword("and"),
  keyword_or: _ => make_keyword("or"),
  keyword_is: _ => make_keyword("is"),
  keyword_not: _ => make_keyword("not"),
  keyword_enable: _ => make_keyword("enable"),
  keyword_disable: _ => make_keyword("disable"),
  keyword_force: _ => make_keyword("force"),
  keyword_ignore: _ => make_keyword("ignore"),
  keyword_using: _ => make_keyword("using"),
  keyword_use: _ => make_keyword("use"),
  keyword_index: _ => make_keyword("index"),
  keyword_include: _ => make_keyword("include"),
  keyword_for: _ => make_keyword("for"),
  keyword_if: _ => make_keyword("if"),
  keyword_exists: _ => make_keyword("exists"),
  keyword_auto_increment: _ => make_keyword("auto_increment"),
  keyword_generated: _ => make_keyword("generated"),
  keyword_always: _ => make_keyword("always"),
  keyword_collate: _ => make_keyword("collate"),
  keyword_character: _ => make_keyword("character"),
  keyword_engine: _ => make_keyword("engine"),
  keyword_default: _ => make_keyword("default"),
  keyword_cascade: _ => make_keyword("cascade"),
  keyword_restrict: _ => make_keyword("restrict"),
  keyword_with: _ => make_keyword("with"),
  keyword_without: _ => make_keyword("without"),
  keyword_no: _ => make_keyword("no"),
  keyword_data: _ => make_keyword("data"),
  keyword_type: _ => make_keyword("type"),
  keyword_refresh: _ => make_keyword("refresh"),
  keyword_rename: _ => make_keyword("rename"),
  keyword_to: _ => make_keyword("to"),
  keyword_database: _ => make_keyword("database"),
  keyword_schema: _ => make_keyword("schema"),
  keyword_public: _ => make_keyword("public"),
  keyword_owner: _ => make_keyword("owner"),
  keyword_user: _ => make_keyword("user"),
  keyword_current_user: _ => make_keyword("current_user"),
  keyword_session_user: _ => make_keyword("session_user"),
  keyword_admin: _ => make_keyword("admin"),
  keyword_password: _ => make_keyword("password"),
  keyword_encrypted: _ => make_keyword("encrypted"),
  keyword_valid: _ => make_keyword("valid"),
  keyword_until: _ => make_keyword("until"),
  keyword_connection: _ => make_keyword("connection"),
  keyword_role: _ => make_keyword("role"),
  keyword_current_role: _ => make_keyword("current_role"),
  keyword_reset: _ => make_keyword("reset"),
  keyword_unset: _ => make_keyword("unset"),
  keyword_temp: _ => make_keyword("temp"),
  keyword_temporary: _ => make_keyword("temporary"),
  keyword_unlogged: _ => make_keyword("unlogged"),
  keyword_logged: _ => make_keyword("logged"),
  keyword_cycle: _ => make_keyword("cycle"),
  keyword_union: _ => make_keyword("union"),
  keyword_all: _ => make_keyword("all"),
  keyword_any: _ => make_keyword("any"),
  keyword_some: _ => make_keyword("some"),
  keyword_intersect: _ => make_keyword("intersect"),
  keyword_returning: _ => make_keyword("returning"),
  keyword_begin: _ => make_keyword("begin"),
  keyword_commit: _ => make_keyword("commit"),
  keyword_rollback: _ => make_keyword("rollback"),
  keyword_abort: _ => make_keyword("abort"),
  keyword_fail: _ => make_keyword("fail"),
  keyword_transaction: _ => make_keyword("transaction"),
  keyword_over: _ => make_keyword("over"),
  keyword_nulls: _ => make_keyword("nulls"),
  keyword_first: _ => make_keyword("first"),
  keyword_after: _ => make_keyword("after"),
  keyword_before: _ => make_keyword("before"),
  keyword_last: _ => make_keyword("last"),
  keyword_window: _ => make_keyword("window"),
  keyword_range: _ => make_keyword("range"),
  keyword_groups: _ => make_keyword("groups"),
  keyword_between: _ => make_keyword("between"),
  keyword_unbounded: _ => make_keyword("unbounded"),
  keyword_preceding: _ => make_keyword("preceding"),
  keyword_following: _ => make_keyword("following"),
  keyword_permissive: _ => make_keyword("permissive"),
  keyword_restrictive: _ => make_keyword("restrictive"),
  keyword_exclude: _ => make_keyword("exclude"),
  keyword_current: _ => make_keyword("current"),
  keyword_row: _ => make_keyword("row"),
  keyword_fetch: _ => make_keyword("fetch"),
  keyword_ties: _ => make_keyword("ties"),
  keyword_others: _ => make_keyword("others"),
  keyword_only: _ => make_keyword("only"),
  keyword_unique: _ => make_keyword("unique"),
  keyword_foreign: _ => make_keyword("foreign"),
  keyword_references: _ => make_keyword("references"),
  keyword_concurrently: _ => make_keyword("concurrently"),
  keyword_btree: _ => make_keyword("btree"),
  keyword_hash: _ => make_keyword("hash"),
  keyword_gist: _ => make_keyword("gist"),
  keyword_spgist: _ => make_keyword("spgist"),
  keyword_gin:  _ => make_keyword("gin"),
  keyword_brin: _ => make_keyword("brin"),
  keyword_like: _ => make_keyword("like"),
  keyword_rlike: _ => choice(make_keyword("rlike"),make_keyword("regexp")),
  keyword_similar: _ => make_keyword("similar"),

  keyword_conflict: _ => make_keyword("conflict"),
  keyword_do: _ => make_keyword("do"),
  keyword_nothing: _ => make_keyword("nothing"),
  keyword_high_priority: _ => make_keyword("high_priority"),
  keyword_low_priority: _ => make_keyword("low_priority"),
  keyword_delayed: _ => make_keyword("delayed"),
  keyword_recursive: _ => make_keyword("recursive"),
  keyword_cascaded: _ => make_keyword("cascaded"),
  keyword_local: _ => make_keyword("local"),
  keyword_current_timestamp: _ => make_keyword("current_timestamp"),
  keyword_check: _ => make_keyword("check"),
  keyword_option: _ => make_keyword("option"),
  keyword_vacuum: _ => make_keyword("vacuum"),
  keyword_wait: _ => make_keyword("wait"),
  keyword_nowait: _ => make_keyword("nowait"),
  keyword_attribute: _ => make_keyword("attribute"),
  keyword_authorization: _ => make_keyword("authorization"),
  keyword_action: _ => make_keyword("action"),
  keyword_copy: _ => make_keyword("copy"),
  keyword_stdin: _ => make_keyword("stdin"),
  keyword_freeze: _ => make_keyword("freeze"),
  keyword_escape: _ => make_keyword("escape"),
  keyword_encoding: _ => make_keyword("encoding"),
  keyword_force_quote: _ => make_keyword("force_quote"),
  keyword_quote: _ => make_keyword("quote"),
  keyword_force_null: _ => make_keyword("force_null"),
  keyword_force_not_null: _ => make_keyword("force_not_null"),
  keyword_header: _ => make_keyword("header"),
  keyword_match: _ => make_keyword("match"),
  keyword_program: _ => make_keyword("program"),
  keyword_plain: _ => make_keyword("plain"),
  keyword_extended: _ => make_keyword("extended"),
  keyword_main: _ => make_keyword("main"),
  keyword_storage: _ => make_keyword("storage"),
  keyword_compression: _ => make_keyword("compression"),
  keyword_while: _ => make_keyword("while"),

  // Delta / Databricks keywords
  keyword_retain: _ => make_keyword("retain"),
  keyword_hours: _ => make_keyword("hours"),
  keyword_dry: _ => make_keyword("dry"),
  keyword_run: _ => make_keyword("run"),
  keyword_zorder: _ => make_keyword("zorder"),
  keyword_restore: _ => make_keyword("restore"),
  keyword_convert: _ => make_keyword("convert"),
  keyword_delta: _ => make_keyword("delta"),
  keyword_fsck: _ => make_keyword("fsck"),
  keyword_repair: _ => make_keyword("repair"),
  keyword_reorg: _ => make_keyword("reorg"),
  keyword_apply: _ => make_keyword("apply"),
  keyword_purge: _ => make_keyword("purge"),
  keyword_generate: _ => make_keyword("generate"),
  keyword_msck: _ => make_keyword("msck"),
  keyword_partitions: _ => make_keyword("partitions"),
  keyword_sync: _ => make_keyword("sync"),

  // Unity Catalog / grant keywords
  keyword_grant: _ => make_keyword("grant"),
  keyword_revoke: _ => make_keyword("revoke"),
  keyword_deny: _ => make_keyword("deny"),
  keyword_privileges: _ => make_keyword("privileges"),
  keyword_service: _ => make_keyword("service"),
  keyword_principal: _ => make_keyword("principal"),
  keyword_recipient: _ => make_keyword("recipient"),
  keyword_metastore: _ => make_keyword("metastore"),
  keyword_volume: _ => make_keyword("volume"),
  keyword_credential: _ => make_keyword("credential"),
  keyword_share: _ => make_keyword("share"),
  keyword_files: _ => make_keyword("files"),
  keyword_file: _ => make_keyword("file"),
  keyword_catalog: _ => make_keyword("catalog"),

  keyword_describe: _ => make_keyword("describe"),
  keyword_query: _ => make_keyword("query"),

  // Sprint 1+ Databricks / Spark SQL keywords
  // SELECT extensions (#2)
  keyword_qualify: _ => make_keyword("qualify"),
  keyword_pivot: _ => make_keyword("pivot"),
  keyword_unpivot: _ => make_keyword("unpivot"),
  keyword_tablesample: _ => make_keyword("tablesample"),
  keyword_percent: _ => make_keyword("percent"),
  keyword_bucket: _ => make_keyword("bucket"),
  keyword_cluster: _ => make_keyword("cluster"),
  keyword_distribute: _ => make_keyword("distribute"),
  keyword_transform: _ => make_keyword("transform"),
  keyword_clustered: _ => make_keyword("clustered"),
  keyword_buckets: _ => make_keyword("buckets"),
  // Plural forms needed for SHOW extensions (#9)
  keyword_catalogs: _ => make_keyword("catalogs"),
  keyword_namespaces: _ => make_keyword("namespaces"),
  keyword_volumes: _ => make_keyword("volumes"),
  keyword_connections: _ => make_keyword("connections"),
  keyword_credentials: _ => make_keyword("credentials"),
  keyword_shares: _ => make_keyword("shares"),
  keyword_recipients: _ => make_keyword("recipients"),
  keyword_providers: _ => make_keyword("providers"),
  // CREATE / DROP / SHOW / DESCRIBE extensions (#3, #5, #9, #10)
  keyword_namespace: _ => make_keyword("namespace"),
  keyword_streaming: _ => make_keyword("streaming"),
  keyword_live: _ => make_keyword("live"),
  keyword_provider: _ => make_keyword("provider"),
  keyword_options: _ => make_keyword("options"),
  keyword_url: _ => make_keyword("url"),
  keyword_grants: _ => make_keyword("grants"),
  keyword_history: _ => make_keyword("history"),
  keyword_detail: _ => make_keyword("detail"),
  // SET extensions (#14)
  keyword_global: _ => make_keyword("global"),
  // CACHE extensions (#15)
  keyword_lazy: _ => make_keyword("lazy"),
  keyword_clear: _ => make_keyword("clear"),
  keyword_uncache: _ => make_keyword("uncache"),
  // Resource management (#16)
  keyword_jar: _ => make_keyword("jar"),
  // CREATE FUNCTION Databricks options
  keyword_handler: _ => make_keyword("handler"),
  keyword_environment: _ => make_keyword("environment"),
  keyword_parameter: _ => make_keyword("parameter"),
  keyword_style: _ => make_keyword("style"),
  keyword_shallow: _ => make_keyword("shallow"),
  keyword_deep: _ => make_keyword("deep"),
  keyword_clone: _ => make_keyword("clone"),
  keyword_jars: _ => make_keyword("jars"),
  keyword_archive: _ => make_keyword("archive"),
  keyword_archives: _ => make_keyword("archives"),
  keyword_list: _ => make_keyword("list"),
  // CALL + EXECUTE IMMEDIATE (#13)
  keyword_call: _ => make_keyword("call"),
  // INSERT / LOAD extensions (#12)
  keyword_changes: _ => make_keyword("changes"),
  keyword_directory: _ => make_keyword("directory"),
  keyword_load: _ => make_keyword("load"),
  keyword_inpath: _ => make_keyword("inpath"),
  // ALTER TABLE extensions — Iceberg branches/tags (#4)
  keyword_branch: _ => make_keyword("branch"),
  keyword_tag: _ => make_keyword("tag"),
  keyword_identity: _ => make_keyword("identity"),
  keyword_position: _ => make_keyword("position"),
  keyword_distributed: _ => make_keyword("distributed"),
  keyword_ordered: _ => make_keyword("ordered"),
  // Procedural scripting (#17)
  keyword_elseif: _ => make_keyword("elseif"),
  keyword_loop: _ => make_keyword("loop"),
  keyword_repeat: _ => make_keyword("repeat"),
  keyword_signal: _ => make_keyword("signal"),
  keyword_resignal: _ => make_keyword("resignal"),
  keyword_leave: _ => make_keyword("leave"),
  keyword_iterate: _ => make_keyword("iterate"),
  keyword_diagnostics: _ => make_keyword("diagnostics"),
  keyword_sqlstate: _ => make_keyword("sqlstate"),
  keyword_returned_sqlstate: _ => make_keyword("returned_sqlstate"),
  keyword_message_text: _ => make_keyword("message_text"),
  keyword_message: _ => make_keyword("message"),
  keyword_condition: _ => make_keyword("condition"),
  keyword_get: _ => make_keyword("get"),
  // MySQL SHOW / DESCRIBE extensions (#2d)
  keyword_databases: _ => make_keyword("databases"),
  keyword_processlist: _ => make_keyword("processlist"),
  keyword_status: _ => make_keyword("status"),
  keyword_warnings: _ => make_keyword("warnings"),
  keyword_errors: _ => make_keyword("errors"),
  keyword_variables: _ => make_keyword("variables"),
  keyword_indexes: _ => make_keyword("indexes"),
  // BigQuery native types and functions (#2e)
  keyword_int64:      _ => make_keyword("int64"),
  keyword_float64:    _ => make_keyword("float64"),
  keyword_bytes:      _ => make_keyword("bytes"),
  keyword_bignumeric: _ => make_keyword("bignumeric"),
  keyword_geography:  _ => make_keyword("geography"),
  keyword_datetime:   _ => make_keyword("datetime"),
  keyword_unnest:     _ => make_keyword("unnest"),
  keyword_flatten:    _ => make_keyword("flatten"),
  // PostgreSQL partitioning and table options (#2h)
  keyword_inherits:   _ => make_keyword("inherits"),
  keyword_including:  _ => make_keyword("including"),
  keyword_excluding:  _ => make_keyword("excluding"),
  // Oracle PL/SQL procedural keywords (#3a)
  keyword_elsif:      _ => make_keyword("elsif"),
  keyword_exit:       _ => make_keyword("exit"),
  // Spark 4.x (#21)
  keyword_var: _ => make_keyword("var"),
  keyword_variable: _ => make_keyword("variable"),
  keyword_variant: _ => make_keyword("variant"),

  // Common dialect types
  keyword_string: _ => make_keyword("string"),

  // Snowflake dialect keywords
  keyword_at: _ => make_keyword("at"),
  keyword_one: _ => make_keyword("one"),
  keyword_per: _ => make_keyword("per"),
  keyword_past: _ => make_keyword("past"),
  keyword_next: _ => make_keyword("next"),
  keyword_match_recognize: _ => make_keyword("match_recognize"),
  keyword_measures: _ => make_keyword("measures"),
  keyword_pattern: _ => make_keyword("pattern"),
  keyword_define: _ => make_keyword("define"),
  keyword_skip: _ => make_keyword("skip"),
  keyword_let: _ => make_keyword("let"),
  keyword_raise: _ => make_keyword("raise"),
  keyword_exception: _ => make_keyword("exception"),
  keyword_task: _ => make_keyword("task"),
  keyword_stream: _ => make_keyword("stream"),
  keyword_dynamic: _ => make_keyword("dynamic"),
  keyword_warehouse: _ => make_keyword("warehouse"),
  keyword_schedule: _ => make_keyword("schedule"),
  keyword_secure: _ => make_keyword("secure"),
  keyword_masking: _ => make_keyword("masking"),
  keyword_target_lag: _ => make_keyword("target_lag"),
  keyword_access: _ => make_keyword("access"),
  keyword_secondary: _ => make_keyword("secondary"),
  keyword_roles: _ => make_keyword("roles"),

  keyword_source: _ => make_keyword("source"),
  keyword_except: _ => make_keyword("except"),

  keyword_trigger: _ => make_keyword('trigger'),
  keyword_function: _ => make_keyword("function"),
  keyword_returns: _ => make_keyword("returns"),
  keyword_return: _ => make_keyword("return"),
  keyword_setof: _ => make_keyword("setof"),
  keyword_atomic: _ => make_keyword("atomic"),
  keyword_declare: _ => make_keyword("declare"),
  keyword_language: _ => make_keyword("language"),
  keyword_immutable: _ => make_keyword("immutable"),
  keyword_stable: _ => make_keyword("stable"),
  keyword_volatile: _ => make_keyword("volatile"),
  keyword_leakproof: _ => make_keyword("leakproof"),
  keyword_parallel: _ => make_keyword("parallel"),
  keyword_safe: _ => make_keyword("safe"),
  keyword_unsafe: _ => make_keyword("unsafe"),
  keyword_restricted: _ => make_keyword("restricted"),
  keyword_called: _ => make_keyword("called"),
  keyword_input: _ => make_keyword("input"),
  keyword_strict: _ => make_keyword("strict"),
  keyword_cost: _ => make_keyword("cost"),
  keyword_rows: _ => make_keyword("rows"),
  keyword_support: _ => make_keyword("support"),
  keyword_definer: _ => make_keyword("definer"),
  keyword_invoker: _ => make_keyword("invoker"),
  keyword_security: _ => make_keyword("security"),
  keyword_version: _ => make_keyword("version"),
  keyword_extension: _ => make_keyword("extension"),
  keyword_out: _ => make_keyword("out"),
  keyword_inout: _ => make_keyword("inout"),
  keyword_variadic: _ => make_keyword("variadic"),
  keyword_ordinality: _ => make_keyword("ordinality"),

  keyword_session: _ => make_keyword("session"),
  keyword_isolation: _ => make_keyword("isolation"),
  keyword_level: _ => make_keyword("level"),
  keyword_serializable: _ => make_keyword("serializable"),
  keyword_repeatable: _ => make_keyword("repeatable"),
  keyword_read: _ => make_keyword("read"),
  keyword_write: _ => make_keyword("write"),
  keyword_committed: _ => make_keyword("committed"),
  keyword_uncommitted: _ => make_keyword("uncommitted"),
  keyword_deferrable: _ => make_keyword("deferrable"),
  keyword_names: _ => make_keyword("names"),
  keyword_zone: _ => make_keyword("zone"),
  keyword_immediate: _ => make_keyword("immediate"),
  keyword_deferred: _ => make_keyword("deferred"),
  keyword_constraints    : _ => make_keyword("constraints"),
  keyword_snapshot: _ => make_keyword("snapshot"),
  keyword_appends: _ => make_keyword("appends"),
  keyword_characteristics: _ => make_keyword("characteristics"),
  keyword_follows: _ => make_keyword("follows"),
  keyword_precedes: _ => make_keyword("precedes"),
  keyword_each: _ => make_keyword("each"),
  keyword_instead: _ => make_keyword("instead"),
  keyword_of: _ => make_keyword("of"),
  keyword_initially: _ => make_keyword("initially"),
  keyword_old: _ => make_keyword("old"),
  keyword_new: _ => make_keyword("new"),
  keyword_referencing: _ => make_keyword("referencing"),
  keyword_statement: _ => make_keyword("statement"),
  keyword_execute: _ => make_keyword("execute"),
  keyword_procedure: _ => make_keyword("procedure"),
  keyword_object_id: _ => make_keyword("object_id"),

  // Hive Keywords
  keyword_external: _ => make_keyword("external"),
  keyword_stored: _ => make_keyword("stored"),
  keyword_virtual: _ => make_keyword("virtual"),
  keyword_cached: _ => make_keyword("cached"),
  keyword_uncached: _ => make_keyword("uncached"),
  keyword_replication: _ => make_keyword("replication"),
  keyword_tblproperties: _ => make_keyword("tblproperties"),
  keyword_compute: _ => make_keyword("compute"),
  keyword_stats: _ => make_keyword("stats"),
  keyword_statistics: _ => make_keyword("statistics"),
  keyword_optimize: _ => make_keyword("optimize"),
  keyword_rewrite: _ => make_keyword("rewrite"),
  keyword_bin_pack: _ => make_keyword("bin_pack"),
  keyword_incremental: _ => make_keyword("incremental"),
  keyword_location: _ => make_keyword("location"),
  keyword_partitioned: _ => make_keyword("partitioned"),
  keyword_comment: _ => make_keyword("comment"),
  keyword_sort: _ => make_keyword("sort"),
  keyword_sorted: _ => make_keyword("sorted"),
  keyword_format: _ => make_keyword("format"),
  keyword_delimited: _ => make_keyword("delimited"),
  keyword_delimiter: _ => make_keyword("delimiter"),
  keyword_fields: _ => make_keyword("fields"),
  keyword_terminated: _ => make_keyword("terminated"),
  keyword_escaped: _ => make_keyword("escaped"),
  keyword_lines: _ => make_keyword("lines"),
  keyword_cache: _ => make_keyword("cache"),
  keyword_metadata: _ => make_keyword("metadata"),
  keyword_noscan: _ => make_keyword("noscan"),

  // Hive file formats
  keyword_parquet: _ => make_keyword("parquet"),
  keyword_rcfile: _ => make_keyword("rcfile"),
  keyword_csv: _ => make_keyword("csv"),
  keyword_textfile: _ => make_keyword("textfile"),
  keyword_avro: _ => make_keyword("avro"),
  keyword_sequencefile: _ => make_keyword("sequencefile"),
  keyword_orc: _ => make_keyword("orc"),
  keyword_jsonfile: _ => make_keyword("jsonfile"),

  // Operators
  is_not: $ => prec.left(seq($.keyword_is, $.keyword_not)),
  not_like: $ => seq($.keyword_not, $.keyword_like),
  not_rlike: $ => seq($.keyword_not, $.keyword_rlike),
  similar_to: $ => seq($.keyword_similar, $.keyword_to),
  not_similar_to: $ => seq($.keyword_not, $.keyword_similar, $.keyword_to),
  distinct_from: $ => seq($.keyword_is, $.keyword_distinct, $.keyword_from),
  not_distinct_from: $ => seq($.keyword_is, $.keyword_not, $.keyword_distinct, $.keyword_from),

  _temporary: $ => choice($.keyword_temp, $.keyword_temporary),
  _not_null: $ => seq($.keyword_not, $.keyword_null),
  _primary_key: $ => seq($.keyword_primary, $.keyword_key),
  _if_exists: $ => seq($.keyword_if, $.keyword_exists),
  _if_not_exists: $ => seq($.keyword_if, $.keyword_not, $.keyword_exists),
  _or_replace: $ => seq($.keyword_or, $.keyword_replace),
  _current_row: $ => seq($.keyword_current, $.keyword_row),
  _exclude_current_row: $ => seq($.keyword_exclude, $.keyword_current, $.keyword_row),
  _exclude_group: $ => seq($.keyword_exclude, $.keyword_group),
  _exclude_no_others: $ => seq($.keyword_exclude, $.keyword_no, $.keyword_others),
  _exclude_ties: $ => seq($.keyword_exclude, $.keyword_ties),
  _check_option: $ => seq($.keyword_check, $.keyword_option),
  direction: $ => choice($.keyword_desc, $.keyword_asc),

  // Types
  keyword_null: _ => make_keyword("null"),
  keyword_true: _ => make_keyword("true"),
  keyword_false: _ => make_keyword("false"),

  keyword_boolean: _ => make_keyword("boolean"),
  keyword_bit: _ => make_keyword("bit"),
  keyword_binary: _ => make_keyword("binary"),
  keyword_varbinary: _ => make_keyword("varbinary"),

  keyword_smallint: _ => make_keyword("smallint"),
  keyword_int: _ => choice(make_keyword("int"), make_keyword("integer")),
  keyword_bigint: _ => make_keyword("bigint"),
  keyword_decimal: _ => make_keyword("decimal"),
  keyword_numeric: _ => make_keyword("numeric"),
  keyword_real: _ => make_keyword("real"),
  keyword_float: _ => make_keyword("float"),
  keyword_double: _ => make_keyword("double"),
  keyword_precision: _ => make_keyword("precision"),

  keyword_varying: _ => make_keyword("varying"),

  keyword_char: _ => choice(make_keyword("char"), make_keyword("character")),
  keyword_nchar: _ => make_keyword("nchar"),
  keyword_varchar: $ => choice(
    make_keyword("varchar"),
    seq(
      make_keyword("character"),
      $.keyword_varying,
    )
  ),
  keyword_nvarchar: _ => make_keyword("nvarchar"),
  keyword_text: _ => make_keyword("text"),

  keyword_json: _ => make_keyword("json"),
  keyword_xml: _ => make_keyword("xml"),

  keyword_enum: _ => make_keyword("enum"),

  keyword_date: _ => make_keyword("date"),
  keyword_time: _ => make_keyword("time"),
  keyword_timestamp: _ => make_keyword("timestamp"),
  keyword_interval: _ => make_keyword("interval"),

  keyword_array: _ => make_keyword("array"), // not included in _type since it's a constructor literal

  // BigQuery-specific keywords
  keyword_struct: _ => make_keyword("struct"),
  keyword_export: _ => make_keyword("export"),
  keyword_model: _ => make_keyword("model"),
  keyword_ml: _ => make_keyword("ml"),
  keyword_predict: _ => make_keyword("predict"),
  keyword_evaluate: _ => make_keyword("evaluate"),
  keyword_assert: _ => make_keyword("assert"),
  keyword_continue: _ => make_keyword("continue"),
  keyword_error: _ => make_keyword("error"),

  // PostgreSQL-specific types (non-ANSI)
  keyword_oid: _ => make_keyword("oid"),
  keyword_oids: _ => make_keyword("oids"),
  keyword_name: _ => make_keyword("name"),
  keyword_regclass: _ => make_keyword("regclass"),
  keyword_regnamespace: _ => make_keyword("regnamespace"),
  keyword_regproc: _ => make_keyword("regproc"),
  keyword_regtype: _ => make_keyword("regtype"),

  // ANSI SQL — TRIM(BOTH|LEADING|TRAILING x FROM y)
  keyword_both: _ => make_keyword("both"),
  keyword_leading: _ => make_keyword("leading"),
  keyword_trailing: _ => make_keyword("trailing"),
  keyword_trim: _ => make_keyword("trim"),

  // ANSI SQL — WITHIN GROUP (ORDER BY ...)
  keyword_within: _ => make_keyword("within"),

}
