name: Publish Packages
on:
  push:
    branch: publish-fixes-test

jobs:
  pypi-publish:
    uses: DerekStride/tree-sitter-workflows/.github/workflows/package-pypi.yml@test-rebuild
    with:
      python-version: 3.11
      generate: true
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
